services:
  back-end:
    image:  softy-pinko-back-end:task4
    build: 
      context: ./back-end
      dockerfile: Dockerfile

  front-end:
    image: softy-pinko-front-end:task4
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end
  
  proxy:
      image: softy-pinko-front-end:task5
      build:
        context: ./proxy
        dockerfile: Dockerfile
      ports:
        - "80:80"
      depends_on:
        - back-end
        - front-end
  

